//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicQualification
    {
        public int QualID { get; set; }
        public Nullable<int> IPPSNO { get; set; }
        public Nullable<int> AcadID { get; set; }
        public string Category { get; set; }
        public Nullable<int> AcadInstID { get; set; }
        public Nullable<int> YearFrom { get; set; }
        public Nullable<int> YearTo { get; set; }
        public string Award { get; set; }
        public Nullable<short> Action { get; set; }
    
        public virtual AcademicCours AcademicCours { get; set; }
        public virtual AcademicInstitution AcademicInstitution { get; set; }
    }
}
