//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardCancelTable
    {
        public int CancelID { get; set; }
        public int CardID { get; set; }
        public string CancleReason { get; set; }
        public string CancelDate { get; set; }
    }
}
