//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class currentDeployment
    {
        public int id { get; set; }
        public Nullable<int> id_2 { get; set; }
        public Nullable<int> sectionID2 { get; set; }
        public string FNumber { get; set; }
        public Nullable<int> DirectorateID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> unitID { get; set; }
        public Nullable<int> sectionID { get; set; }
        public Nullable<int> regionID { get; set; }
        public Nullable<int> districtID { get; set; }
        public Nullable<int> stationID { get; set; }
        public string post { get; set; }
        public string Responsibility { get; set; }
        public Nullable<short> state { get; set; }
        public string RecordedBy { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
        public string currentStatus { get; set; }
        public string Reasons { get; set; }
        public Nullable<System.DateTime> DateOfPosting { get; set; }
    }
}
