//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public int DistrictID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string District1 { get; set; }
        public string Figures { get; set; }
        public string Region { get; set; }
        public Nullable<int> Ranking { get; set; }
    }
}
