//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportData
    {
        public int id { get; set; }
        public string Rank { get; set; }
        public string ForceNo { get; set; }
        public string FileNo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Sex { get; set; }
        public string Religion { get; set; }
        public string Dateofbirth { get; set; }
        public string Placeofbirth { get; set; }
        public string MaritalStatus { get; set; }
        public string TypeOfMarriage { get; set; }
        public string DateOfMarriage { get; set; }
        public string Nationality { get; set; }
        public string Tribe { get; set; }
        public string BloodGroup { get; set; }
        public string WarrantCardNo { get; set; }
        public string DateOfIssue { get; set; }
        public string PassportNo { get; set; }
        public string PassportDateIssued { get; set; }
        public string PassportExpiryDate { get; set; }
        public string IssuingAuthority { get; set; }
        public string Directorate { get; set; }
        public string Department { get; set; }
        public string Region { get; set; }
        public string District { get; set; }
        public string Station { get; set; }
    }
}
