//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportedDeployableData
    {
        public int id { get; set; }
        public string Rank { get; set; }
        public string ForceNo { get; set; }
        public string FileNo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Directorate { get; set; }
        public string Department { get; set; }
        public string Region { get; set; }
        public string District { get; set; }
        public string Station { get; set; }
    }
}
