//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Live_HRMISEntities1 : DbContext
    {
        public Live_HRMISEntities1()
            : base("name=Live_HRMISEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicCours> AcademicCourses { get; set; }
        public virtual DbSet<AcademicInstitution> AcademicInstitutions { get; set; }
        public virtual DbSet<AcademicQualification> AcademicQualifications { get; set; }
        public virtual DbSet<ACCOMMODATION> ACCOMMODATIONs { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<AWARDS_AND_COMMENDATIONS> AWARDS_AND_COMMENDATIONS { get; set; }
        public virtual DbSet<Awol_Counter> Awol_Counter { get; set; }
        public virtual DbSet<BankBranch> BankBranches { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BloodGroup> BloodGroups { get; set; }
        public virtual DbSet<CardCancelTable> CardCancelTables { get; set; }
        public virtual DbSet<Colour> Colours { get; set; }
        public virtual DbSet<contract> contracts { get; set; }
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DEPENDANT> DEPENDANTS { get; set; }
        public virtual DbSet<Deployement> Deployements { get; set; }
        public virtual DbSet<DEPLOYMENT_EMPLOYMENT> DEPLOYMENT_EMPLOYMENT { get; set; }
        public virtual DbSet<Desertion_Table> Desertion_Table { get; set; }
        public virtual DbSet<DETAILS_OF_EMPLOYMENT> DETAILS_OF_EMPLOYMENT { get; set; }
        public virtual DbSet<Directorate> Directorates { get; set; }
        public virtual DbSet<Discipline> Disciplines { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<EDUCATION_AND_QUALIFICATIONS_Old> EDUCATION_AND_QUALIFICATIONS_Old { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Enlistment> Enlistments { get; set; }
        public virtual DbSet<Error> Errors { get; set; }
        public virtual DbSet<EXIT> EXITs { get; set; }
        public virtual DbSet<ExitName> ExitNames { get; set; }
        public virtual DbSet<EyeColour> EyeColours { get; set; }
        public virtual DbSet<FAMILY_INFORMATION> FAMILY_INFORMATION { get; set; }
        public virtual DbSet<ForceStrength> ForceStrengths { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<HairColour> HairColours { get; set; }
        public virtual DbSet<HEALTH> HEALTHs { get; set; }
        public virtual DbSet<HOME_ADDRESS> HOME_ADDRESS { get; set; }
        public virtual DbSet<ImageReport> ImageReports { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<ImportData> ImportDatas { get; set; }
        public virtual DbSet<ImportedDeployableData> ImportedDeployableDatas { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<IssuingAuthority> IssuingAuthorities { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LANGUAGES_PROFFECIENCY> LANGUAGES_PROFFECIENCY { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<NEXT_OF_KIN1> NEXT_OF_KIN1 { get; set; }
        public virtual DbSet<NEXT_OF_KIN2> NEXT_OF_KIN2 { get; set; }
        public virtual DbSet<Offence> Offences { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<OTHER_RELATED_COURSES_ATTENDED> OTHER_RELATED_COURSES_ATTENDED { get; set; }
        public virtual DbSet<PARENT> PARENTS { get; set; }
        public virtual DbSet<Parish> Parishes { get; set; }
        public virtual DbSet<PAY_AND_WELFARE> PAY_AND_WELFARE { get; set; }
        public virtual DbSet<Performance> Performances { get; set; }
        public virtual DbSet<PERSONAL_INFORMATION> PERSONAL_INFORMATION { get; set; }
        public virtual DbSet<PHYSICAL_ADDRESSES> PHYSICAL_ADDRESSES { get; set; }
        public virtual DbSet<PHYSICAL_FEATURES> PHYSICAL_FEATURES { get; set; }
        public virtual DbSet<POLICE_RELATED_COURSES_ATTENDED> POLICE_RELATED_COURSES_ATTENDED { get; set; }
        public virtual DbSet<PoliceCourseInstitution> PoliceCourseInstitutions { get; set; }
        public virtual DbSet<PoliceCours> PoliceCourses { get; set; }
        public virtual DbSet<PolicePost> PolicePosts { get; set; }
        public virtual DbSet<PoliceStation> PoliceStations { get; set; }
        public virtual DbSet<Profession> Professions { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<Rank> Ranks { get; set; }
        public virtual DbSet<RECORD_ON_DISCIPLINE> RECORD_ON_DISCIPLINE { get; set; }
        public virtual DbSet<RECORD_ON_PROMOTION> RECORD_ON_PROMOTION { get; set; }
        public virtual DbSet<RECORD_ON_TRANSFER> RECORD_ON_TRANSFER { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SalaryScale> SalaryScales { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Sections2> Sections2 { get; set; }
        public virtual DbSet<Sentence> Sentences { get; set; }
        public virtual DbSet<SPC_Contracts> SPC_Contracts { get; set; }
        public virtual DbSet<STAFF_LEAVE> STAFF_LEAVE { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<StatusDescriptionTable> StatusDescriptionTables { get; set; }
        public virtual DbSet<StatusName> StatusNames { get; set; }
        public virtual DbSet<Subcounty> Subcounties { get; set; }
        public virtual DbSet<Temp_Dependants_Table> Temp_Dependants_Table { get; set; }
        public virtual DbSet<Temp_Family_Info> Temp_Family_Info { get; set; }
        public virtual DbSet<TestTable> TestTables { get; set; }
        public virtual DbSet<Titles1> Titles1 { get; set; }
        public virtual DbSet<Tribe> Tribes { get; set; }
        public virtual DbSet<tv> tvs { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<Units2> Units2 { get; set; }
        public virtual DbSet<Userlog> Userlogs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Village> Villages { get; set; }
        public virtual DbSet<WarrantSetting> WarrantSettings { get; set; }
        public virtual DbSet<WarrantTable> WarrantTables { get; set; }
        public virtual DbSet<WarrantUser> WarrantUsers { get; set; }
        public virtual DbSet<WarrantUserlog> WarrantUserlogs { get; set; }
        public virtual DbSet<WCardTable> WCardTables { get; set; }
        public virtual DbSet<WIssueTable> WIssueTables { get; set; }
        public virtual DbSet<Year> Years { get; set; }
        public virtual DbSet<ConfirmedDistrictsAndSubcounty> ConfirmedDistrictsAndSubcounties { get; set; }
        public virtual DbSet<currentDeployment> currentDeployments { get; set; }
        public virtual DbSet<NominalRoll> NominalRolls { get; set; }
        public virtual DbSet<NominalRollsGeneral> NominalRollsGenerals { get; set; }
        public virtual DbSet<PoliceStaffList> PoliceStaffLists { get; set; }
        public virtual DbSet<Query> Queries { get; set; }
    }
}
