//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominalRoll
    {
        public int sNo { get; set; }
        public Nullable<int> empID { get; set; }
        public string Jurisdiction { get; set; }
        public Nullable<System.DateTime> DatePromoted { get; set; }
        public string Education { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<short> state { get; set; }
    }
}
