//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominalRollsGeneral
    {
        public int sNo { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string FNo { get; set; }
        public Nullable<int> RankID { get; set; }
        public string Sex { get; set; }
        public string TinNo { get; set; }
        public string IPPSNo { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public Nullable<System.DateTime> DoE { get; set; }
        public Nullable<System.DateTime> DoP { get; set; }
        public Nullable<System.DateTime> DoProm { get; set; }
        public Nullable<int> BankID { get; set; }
        public string AccountNo { get; set; }
        public string Education { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> TribeID { get; set; }
        public string TelNo { get; set; }
        public string NIN { get; set; }
        public Nullable<System.DateTime> DatePrepared { get; set; }
        public Nullable<int> StationID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string ExitStatus { get; set; }
        public string Location { get; set; }
        public Nullable<int> sectionID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> TitleID { get; set; }
    }
}
