//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PAY_AND_WELFARE
    {
        public int WelfareID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string FNumber { get; set; }
        public string IPPSNO { get; set; }
        public Nullable<int> SalaryScaleID { get; set; }
        public string MonthlySalary { get; set; }
        public string AccountNo { get; set; }
        public string AccountTitle { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string TINNO { get; set; }
        public string PayrollStatus { get; set; }
        public string ReasonforInactive { get; set; }
        public string RecordedBy { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateRecorded { get; set; }
    }
}
