//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public int performance_id { get; set; }
        public Nullable<int> perf_january { get; set; }
        public Nullable<int> perf_feburary { get; set; }
        public Nullable<int> perf_march { get; set; }
        public Nullable<int> perf_april { get; set; }
        public Nullable<int> perf_may { get; set; }
        public Nullable<int> perf_june { get; set; }
        public Nullable<int> perf_july { get; set; }
        public Nullable<int> perf_august { get; set; }
        public Nullable<int> perf_sept { get; set; }
        public Nullable<int> perf_oct { get; set; }
        public Nullable<int> perf_nov { get; set; }
        public Nullable<int> perf_dec { get; set; }
    }
}
