//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAL_INFORMATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONAL_INFORMATION()
        {
            this.Desertion_Table = new HashSet<Desertion_Table>();
        }
    
        public int EmpID { get; set; }
        public string Category { get; set; }
        public string ForceNo { get; set; }
        public string FileNo { get; set; }
        public Nullable<int> RankID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> TitleID { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public Nullable<System.DateTime> Dateofbirth { get; set; }
        public string Placeofbirth { get; set; }
        public string MaritalStatus { get; set; }
        public string TypeOfMarriage { get; set; }
        public Nullable<System.DateTime> DateOfMarriage { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> TribeID { get; set; }
        public Nullable<int> BloodGroupID { get; set; }
        public string WarrantCardNo { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportDateIssued { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public Nullable<int> IssuingAuthorityID { get; set; }
        public string Photo { get; set; }
        public string Path { get; set; }
        public string Status { get; set; }
        public string RecordedBy { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
        public Nullable<int> Age { get; set; }
        public string AgeBal { get; set; }
        public string SerialNo { get; set; }
        public string NIN { get; set; }
        public string Passcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Desertion_Table> Desertion_Table { get; set; }
    }
}
