//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PHYSICAL_FEATURES
    {
        public int FeatureID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string FNumber { get; set; }
        public string ColourOfEye { get; set; }
        public string ColourOfHair { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string DressSize { get; set; }
        public string SkirtLength { get; set; }
        public string ShirtCollarSize { get; set; }
        public string TrouserLength { get; set; }
        public string WaistSize { get; set; }
        public string ShoeSize { get; set; }
        public string HeadCapSize { get; set; }
        public string Complexion { get; set; }
        public string DistinguishingFeatures { get; set; }
        public string RecordedBy { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateRecorded { get; set; }
    }
}
