//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliceStaffList
    {
        public Nullable<int> sno { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public string FNumber { get; set; }
        public string Rank { get; set; }
        public Nullable<int> RanKID { get; set; }
        public string Unit { get; set; }
        public string Title { get; set; }
        public string District { get; set; }
        public string Region { get; set; }
        public string Station { get; set; }
        public string Directorate { get; set; }
        public string Department { get; set; }
        public string Sex { get; set; }
        public string MaritalStatus { get; set; }
        public string Tribe { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public System.DateTime DateofEnlistment { get; set; }
        public Nullable<System.DateTime> DateofPosting { get; set; }
        public string PlaceofEnlistment { get; set; }
        public string Qualification { get; set; }
        public string Discipline { get; set; }
        public string YoS { get; set; }
        public int Age { get; set; }
        public Nullable<int> RYoS { get; set; }
        public string Contact { get; set; }
        public string IPPSNO { get; set; }
        public string AccountNo { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public Nullable<System.DateTime> DateofExit { get; set; }
        public string ExitType { get; set; }
        public System.DateTime doN { get; set; }
        public string compNo { get; set; }
        public string currentTime { get; set; }
    }
}
