//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class POLICE_RELATED_COURSES_ATTENDED
    {
        public int PoliceCourseID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> RankID { get; set; }
        public string FNumber { get; set; }
        public Nullable<int> courseID { get; set; }
        public Nullable<int> PCID { get; set; }
        public string Award { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string RecordedBy { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateRecorded { get; set; }
    }
}
