//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECORD_ON_DISCIPLINE
    {
        public int DisciplineID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> RankID { get; set; }
        public string FNumber { get; set; }
        public string sdref_no { get; set; }
        public string everCriminallyCharged { get; set; }
        public string CRB { get; set; }
        public string everDisciplinaryCharged { get; set; }
        public string SD_ref { get; set; }
        public string BOR { get; set; }
        public string GCR { get; set; }
        public Nullable<System.DateTime> Datecommited { get; set; }
        public string NatureofOffence { get; set; }
        public string CommittedFrom { get; set; }
        public string OutCome { get; set; }
        public string RecordedBy { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
    }
}
