//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sections2
    {
        public int sectionID2 { get; set; }
        public int id_2 { get; set; }
        public string Section { get; set; }
    
        public virtual Units2 Units2 { get; set; }
    }
}
