//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_LEAVE
    {
        public int StaffLeaveID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> RankID { get; set; }
        public string FNumber { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string unit { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string LeaveAddress { get; set; }
        public string RecordedBy { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
        public Nullable<int> State { get; set; }
    }
}
