//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int StatusID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> RankID { get; set; }
        public string FNumber { get; set; }
        public string TypeOfStatus { get; set; }
        public string Description { get; set; }
        public string Period { get; set; }
        public string PeriodInFigures { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
    }
}
