//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Family_Info
    {
        public int temp_family { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string Fnumber { get; set; }
        public string SpouseName { get; set; }
        public Nullable<System.DateTime> spouseDateOfbirth { get; set; }
        public string ChildName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> ChildDateOfbirth { get; set; }
        public string RecordedBy { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
        public string Session { get; set; }
    }
}
