//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Dependants_Table
    {
        public int Dep_temp_id { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public string Fnumber { get; set; }
        public string DependantName { get; set; }
        public string RelationShip { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string RecordedBy { get; set; }
        public string Sessions { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
    }
}
