//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string AccessLevel { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string email { get; set; }
        public string telNo { get; set; }
        public Nullable<short> State { get; set; }
        public string LoginStatus { get; set; }
        public string WarrantUser { get; set; }
        public string OTP { get; set; }
    }
}
