//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMIS_PERSONEL_PROFILE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarrantSetting
    {
        public int SettingID { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string signature { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
